name: build-image-metadata
concurrency:
  group: build-image-metadata
on:
  push:
    branches:
      - main
    paths:
      - image-metadata/src/**/*
      - image-metadata/package*.json
      - image-metadata/*.js

permissions:
  contents: write

env:
  AUTHOR_EMAIL: admin+github-actions@tapclap.com
  AUTHOR_NAME: 'Github Actions'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20

      - name: node modules
        working-directory: ./image-metadata
        run: npm ci

      - name: build
        working-directory: ./image-metadata
        run: npm run build

      - name: commit builded action
        run: |
          if git status | grep 'image-metadata/dist/' -q;
          then
            git config --global user.email "${AUTHOR_EMAIL}"
            git config --global user.name "${AUTHOR_NAME}"
            git add ./image-metadata/dist
            git commit -m "built action image-metadata"
            while true; do
              if ! git push origin ${{ github.ref }}:${{ github.ref }}; then
                echo "Push failed, sleep 10 seconds and retrying..."
                git pull --rebase
                sleep 10
                continue
              else
                break
              fi
            done
          fi